"""empty message

Revision ID: 164559be258c
Revises: 8d44e9baf3d4
Create Date: 2021-06-27 08:31:00.379394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164559be258c'
down_revision = '8d44e9baf3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'calendars', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'destinations', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'destinations', type_='foreignkey')
    op.drop_constraint(None, 'calendars', type_='foreignkey')
    # ### end Alembic commands ###
